flag=-Wall -Werror -Wextra

all: main

main:
	gcc main.c $(flag) -o ~/main
	~/./main /Users/andrey/Downloads

clean:
	rm ~/main

rebuild:
	rm ~/main
	gcc main.c $(flag) -o ~/main
	~/./main /Users/andrey/Downloads
