flag=-Wall -Werror -Wextra

all: main

main:
	gcc ff.c -o ~/ff
	~/./ff i

clean:
	rm ~/ff

rebuild:
	rm ~/ff
	gcc ff.c -o ~/ff
	~/./ff Caspar_David_Friedrich_-_Wanderer_above_the_sea_of_fog.jpg repos

install:
	vim  ~/.bash_profile
